USE thebridgehub;

ALTER TABLE Report MODIFY COLUMN report_type ENUM('USER', 'MESSAGE', 'STUDYROOM', 'INAPPROPRIATE_CONTENT', 'SPAM', 'ABUSE', 'SEXUAL', 'VIOLENCE', 'FRAUD', 'OTHER') NOT NULL COMMENT '신고 유형'; 