spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thebridgehub?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 이메일 설정 (Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:bglyk83@gmail.com}
    password: ${GMAIL_PASSWORD:ipbeaplyaqbqmdsy}
    properties:
      mail:
        smtp:
          auth: false   # ❗️ 인증 false
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.koreait.thebridgehub.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT 설정
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.koreait.thebridgehub: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG 